
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Client_Window extends javax.swing.JFrame {

    /*

*/
    public Client_Window() {
        initComponents();
        this.setLocationRelativeTo (null);
        //Border panel_title_border=BorderFactory.createMatteBorder(0, 0, 3, 0, Color.RED);
        //jLabel1_Owner_Title.setBorder(panel_title_border);
         Border panel_title_border=BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(255,255,255));
         jLabel1_Owner_Title.setBorder(panel_title_border);
        
        //set border to jbuttons
        Border button_border=BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(255,255,255));
        jButton_Add_Client.setBorder(button_border);
         jButton_Edit_Client.setBorder(button_border);
         jButton_Remove_Client.setBorder(button_border);
         jButton_Refresh_Client.setBorder(button_border);
         
         fillJtableWithClientsData();
    }
    
    //we will create a function to populate the jtable with all the owners datausing the array list
    //after that when user select an owner from the jtable all information will be displayed in jtext fields
    public void fillJtableWithClientsData()
    {
        P_CLIENT client = new P_CLIENT();
        ArrayList<P_CLIENT> clientsList=client.clientsList();
        //jtable coloumns
        String[] colNames={"ID","First Name","Last Name","Phone","Email","Address"};
        
        //jtable row
        Object [][] rows=new Object[clientsList.size()][6];
        
        //add data from list to rows
        
        for(int i=0; i<clientsList.size(); i++)
        {
            rows[i][0]=clientsList.get(i).getId();
            rows[i][1]=clientsList.get(i).getFname();
            rows[i][2]=clientsList.get(i).getLname();
            rows[i][3]=clientsList.get(i).getPhone();
            rows[i][4]=clientsList.get(i).getEmail();
            rows[i][5]=clientsList.get(i).getAddress();
            
            DefaultTableModel model=new DefaultTableModel (rows, colNames);
        Client_Table.setModel(model);
        
        Client_Table.setRowHeight(40);
        Client_Table.setSelectionBackground(Color.DARK_GRAY);
        Client_Table.getColumnModel().getColumn(0).setPreferredWidth(25);
        Client_Table.getColumnModel().getColumn(5).setPreferredWidth(100);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1_Owner_Title = new javax.swing.JLabel();
        jLabel_ID = new javax.swing.JLabel();
        jTextField_FName = new javax.swing.JTextField();
        jLabel_Name = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jLabel_description = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Address = new javax.swing.JTextArea();
        jButton_Edit_Client = new javax.swing.JButton();
        jButton_Remove_Client = new javax.swing.JButton();
        jButton_Refresh_Client = new javax.swing.JButton();
        jButton_Add_Client = new javax.swing.JButton();
        jLabel_Name1 = new javax.swing.JLabel();
        jTextField_LName = new javax.swing.JTextField();
        jLabel_Name2 = new javax.swing.JLabel();
        jTextField_Phone = new javax.swing.JTextField();
        jLabel_Name3 = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Client_Table = new javax.swing.JTable();
        jButton_Search_Property = new javax.swing.JButton();
        jButton_cb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1_Owner_Title.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel1_Owner_Title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_Owner_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_Owner_Title.setText("CLIENTS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1_Owner_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(509, 509, 509))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1_Owner_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel_ID.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel_ID.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ID.setText("ID :");

        jTextField_FName.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jTextField_FName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_FName.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)));
        jTextField_FName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FNameActionPerformed(evt);
            }
        });

        jLabel_Name.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel_Name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Name.setText("Last Name:");

        jTextField_id.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jTextField_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_id.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)));
        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });

        jLabel_description.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel_description.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_description.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_description.setText("Address:");

        jTextArea_Address.setColumns(20);
        jTextArea_Address.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea_Address.setRows(5);
        jTextArea_Address.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)));
        jScrollPane1.setViewportView(jTextArea_Address);

        jButton_Edit_Client.setBackground(new java.awt.Color(0, 0, 204));
        jButton_Edit_Client.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Edit_Client.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Edit_Client.setText("Edit");
        jButton_Edit_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Edit_ClientActionPerformed(evt);
            }
        });

        jButton_Remove_Client.setBackground(new java.awt.Color(255, 51, 51));
        jButton_Remove_Client.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Remove_Client.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Remove_Client.setText("Remove");
        jButton_Remove_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Remove_ClientActionPerformed(evt);
            }
        });

        jButton_Refresh_Client.setBackground(new java.awt.Color(0, 102, 102));
        jButton_Refresh_Client.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Refresh_Client.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Refresh_Client.setText("Refresh");
        jButton_Refresh_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Refresh_ClientActionPerformed(evt);
            }
        });

        jButton_Add_Client.setBackground(new java.awt.Color(204, 0, 204));
        jButton_Add_Client.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Add_Client.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_Client.setText("Add");
        jButton_Add_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_ClientActionPerformed(evt);
            }
        });

        jLabel_Name1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel_Name1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Name1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Name1.setText("First Name:");

        jTextField_LName.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jTextField_LName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_LName.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)));

        jLabel_Name2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel_Name2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Name2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Name2.setText("Email:");

        jTextField_Phone.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jTextField_Phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Phone.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)));

        jLabel_Name3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel_Name3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Name3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Name3.setText("Phone:");

        jTextField_Email.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jTextField_Email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Email.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)));
        jTextField_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EmailActionPerformed(evt);
            }
        });

        Client_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Client_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Client_TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Client_Table);

        jButton_Search_Property.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton_Search_Property.setText("Search");

        jButton_cb.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_cb.setText("Back");
        jButton_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Name2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Name1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_description)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Search_Property, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextField_FName, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_LName, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_Name3)
                                .addGap(75, 75, 75)
                                .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_cb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Add_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_Edit_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Remove_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton_Refresh_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Search_Property, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_FName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_LName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Name3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Name2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel_description))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Refresh_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Remove_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Edit_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Add_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_cb)
                        .addGap(32, 32, 32))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_FNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FNameActionPerformed

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jButton_Edit_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Edit_ClientActionPerformed
        //edit the client data
        //get the client data
        
        String fname = jTextField_FName.getText();
        String lname = jTextField_LName.getText();
        String phone = jTextField_Phone.getText();
        String email = jTextField_Email.getText();
        String address = jTextArea_Address.getText();
        
         P_CLIENT client = new P_CLIENT();
         try{
             
             int clientId=Integer.valueOf(jTextField_id.getText());
             
              //before editing the owner data we need to check if the required data are empty
              //required data--> first name, last name, phone, address
        
              if(fname.trim().equals("") || lname.trim().equals("") || phone.trim().equals("") || address.trim().equals(""))
        {
        JOptionPane.showMessageDialog(null, "Enter the Required Client Information[first name, last name, phone, address]", "Edit Client", 2);
        }
        else
        {
        if(client.editClientData(new P_CLIENT(clientId, fname, lname, phone, email, address)))
                {
                    JOptionPane.showMessageDialog(null, "Client Data Edited", "Edit Client", 1);
                }else
                {
            JOptionPane.showMessageDialog(null, "Client Data Not Edited", "Edit Client", 2);
                } 
        }
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage() + "Enter a valid Client ID",  "Invalid Id", 0);
        }
        
    }//GEN-LAST:event_jButton_Edit_ClientActionPerformed

    private void jButton_Remove_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Remove_ClientActionPerformed
       try{
            //deleting the selected client from the system
        int clientId=Integer.valueOf(jTextField_id.getText());
        
        P_CLIENT client = new P_CLIENT();
        
        if(jTextField_id.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Enter the Client ID", "Empty ID", 2);
        }
        else
        {
            //show a confirmation message before deleting the type
            int yes_or_no =JOptionPane.showConfirmDialog(null, "Do you want to delete to delete this Owner", "Deleted Owner", JOptionPane.YES_NO_OPTION);
            if(yes_or_no==JOptionPane.YES_OPTION)
            {
                if(client.deleteClient(clientId))
                {
                    JOptionPane.showMessageDialog(null, "Client Data Deleted", "Delete Client", 1);
                }else
                {
                     JOptionPane.showMessageDialog(null, "Operation Failed", "Delete Client", 2);
                }
            }
        }
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage() + "Enter a valid Client ID",  "Invalid Id", 0);
        }
    }//GEN-LAST:event_jButton_Remove_ClientActionPerformed

    private void jButton_Add_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_ClientActionPerformed
        //get client data
        String fname = jTextField_FName.getText();
        String lname = jTextField_LName.getText();
        String phone = jTextField_Phone.getText();
        String email = jTextField_Email.getText();
        String address = jTextArea_Address.getText();
        
        P_CLIENT client = new P_CLIENT();
        
        //before inserting a new client we need to check if the required data are empty
        //required data--> first name, last name, phone, address
        
        if(fname.trim().equals("") || lname.trim().equals("") || phone.trim().equals("") || address.trim().equals(""))
        {
        JOptionPane.showMessageDialog(null, "Enter the Required Client Information[first name, last name, phone, address]", "Add Client", 2);
        }
        else
        {
        if(client.addNewClient(new P_CLIENT(0, fname, lname, phone, email, address)))
                {
                    JOptionPane.showMessageDialog(null, "New Client Add to the system", "Add Client", 1);
                }else
        {
            JOptionPane.showMessageDialog(null, "Client Not Add to the system", "Add Client", 2);
        } 
        }
    }//GEN-LAST:event_jButton_Add_ClientActionPerformed

    private void jTextField_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EmailActionPerformed

    }//GEN-LAST:event_jTextField_EmailActionPerformed

    private void jButton_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cbActionPerformed
       this.dispose();
        Home_Page cw = new Home_Page();
        cw.setVisible(true);
    }//GEN-LAST:event_jButton_cbActionPerformed

    private void jButton_Refresh_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Refresh_ClientActionPerformed
      fillJtableWithClientsData();
    }//GEN-LAST:event_jButton_Refresh_ClientActionPerformed

    private void Client_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Client_TableMouseClicked
       int selectedRowIndex=Client_Table.getSelectedRow();
       jTextField_id.setText(Client_Table.getValueAt(selectedRowIndex, 0).toString());
       jTextField_FName.setText(Client_Table.getValueAt(selectedRowIndex, 1).toString());
       jTextField_LName.setText(Client_Table.getValueAt(selectedRowIndex, 2).toString());
       jTextField_Phone.setText(Client_Table.getValueAt(selectedRowIndex, 3).toString());
       jTextField_Email.setText(Client_Table.getValueAt(selectedRowIndex, 4).toString());
       jTextArea_Address.setText(Client_Table.getValueAt(selectedRowIndex, 5).toString());
    }//GEN-LAST:event_Client_TableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Client_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Client_Table;
    private javax.swing.JButton jButton_Add_Client;
    private javax.swing.JButton jButton_Edit_Client;
    private javax.swing.JButton jButton_Refresh_Client;
    private javax.swing.JButton jButton_Remove_Client;
    private javax.swing.JButton jButton_Search_Property;
    private javax.swing.JButton jButton_cb;
    private javax.swing.JLabel jLabel1_Owner_Title;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_Name1;
    private javax.swing.JLabel jLabel_Name2;
    private javax.swing.JLabel jLabel_Name3;
    private javax.swing.JLabel jLabel_description;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_Address;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_FName;
    private javax.swing.JTextField jTextField_LName;
    private javax.swing.JTextField jTextField_Phone;
    private javax.swing.JTextField jTextField_id;
    // End of variables declaration//GEN-END:variables
}
